//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CCSEntities : DbContext
{
    public CCSEntities()
        : base("name=CCSEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Address> Addresses { get; set; }
    public DbSet<Agency> Agencies { get; set; }
    public DbSet<City> Cities { get; set; }
    public DbSet<Container> Containers { get; set; }
    public DbSet<DistributionType> DistributionTypes { get; set; }
    public DbSet<FoodCategory> FoodCategories { get; set; }
    public DbSet<FoodIn> FoodIns { get; set; }
    public DbSet<FoodSource> FoodSources { get; set; }
    public DbSet<FoodSourceType> FoodSourceTypes { get; set; }
    public DbSet<Location> Locations { get; set; }
    public DbSet<Log> Logs { get; set; }
    public DbSet<State> States { get; set; }
    public DbSet<USDACategory> USDACategories { get; set; }
    public DbSet<User> Users { get; set; }
    public DbSet<Zipcode> Zipcodes { get; set; }
    public DbSet<Template> Templates { get; set; }
    public DbSet<Adjustment> Adjustments { get; set; }
    public DbSet<Audit> Audits { get; set; }
    public DbSet<ErrorLog> ErrorLogs { get; set; }
    public DbSet<FoodOut> FoodOuts { get; set; }
}
